### ISSUE TITLE
JsonApiRenderer doesn't work with DRF 3.0

### ISSUE THREAD

**Issue by simonv3** [kevin-brown/drf-json-api#24]
It doesn't look like it does, but I just wanted to confirm that I'm not missing something.

**Comment by kevin-brown** [comment]
[All of our tests use `ModelViewSet`](https://github.com/kevin-brown/drf-json-api/blob/master/tests/views.py) for the views. Are you running into any issues?

**Comment by simonv3** [comment]
@kevin-brown Yeah, I think I'm just missing a simple thing.

I've recreated the test app you have here, if you want I can copy and paste it in, but I pretty much just copy-pasted it into my app.


When I load any of the URLs in the browser I get:

Environment:

```
Request Method: POST
Request URL: http://localhost:8000/books/people/

Django Version: 1.7.3
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_extensions',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_framework',
 'books',
 'core')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:
File "/Users/simon/src/reading-list/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  137.                 response = response.render()
File "/Users/simon/src/reading-list/venv/lib/python2.7/site-packages/django/template/response.py" in render
  103.             self.content = self.rendered_content
File "/Users/simon/src/reading-list/venv/lib/python2.7/site-packages/rest_framework/response.py" in rendered_content
  59.         ret = renderer.render(self.data, media_type, context)
File "/Users/simon/src/reading-list/venv/lib/python2.7/site-packages/rest_framework/renderers.py" in render
  733.         context = self.get_context(data, accepted_media_type, renderer_context)
File "/Users/simon/src/reading-list/venv/lib/python2.7/site-packages/rest_framework/renderers.py" in get_context
  697.             'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
File "/Users/simon/src/reading-list/venv/lib/python2.7/site-packages/rest_framework/renderers.py" in get_content
  498.         content = renderer.render(data, accepted_media_type, renderer_context)
File "/Users/simon/src/reading-list/venv/lib/python2.7/site-packages/rest_framework_json_api/renderers.py" in render
  65.                 data=data, renderer_context=renderer_context)

Exception Type: WrapperNotApplicable at /books/people/
Exception Value: No acceptable wrappers found for response.
```


my settings.py:
```
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        "rest_framework_json_api.renderers.JsonApiRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
        # Any other renderers
    ),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework_json_api.parsers.JsonApiParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
        # Any other parsers
    ),
}
```

**Comment by kevin-brown** [comment]
_We should really just return the response directly if it can't be wrapped..._

Usually this means that your response isn't a list or doesn't use the standard pagination serializers.

**Comment by simonv3** [comment]
@kevin-brown I'm not sure I understand. I'm using the drf `serializers.HyperlinkedModelSerializer` - should I be setting pagination in the settings?

**Comment by jwhitlock** [comment]
Could you post the native representation?  The output from the standard JSONRenderer (`rest_framework.renderers.JSONRenderer`) should be close enough, if you can't get it directly.

**Comment by simonv3** [comment]
How would I do that?

When I go into the `rest_framework_json_api.renderers.py` and log the `data` variable passed to `render()` I get:

```
ReturnDict([('id', 1), ('url', 'http://localhost:8000/jsonapitest/people/1/'), ('name', u'Test')])
```

**Comment by simonv3** [comment]
I've stripped away everything extraneous and put it in its own repository: 

https://github.com/simonv3/django-rest-framework-json-api-test

Accessing the API here fails with the same error.

**Comment by jwhitlock** [comment]
I suspect a compatibility issue Django REST Framework 3 - `ReturnDict` appears to be new in that version:

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/serializer_helpers.py

**Comment by simonv3** [comment]
Yep, downgrading to Django Rest Framework 2.4 seems to fix it. Any idea what it would take to port this to 3.0?

**Comment by jwhitlock** [comment]
I suspect fully supporting 2.4 will be easy, and 3.0 could be harder but still doable.  I've started a branch [drf24-30](https://github.com/jwhitlock/drf-json-api/tree/drf24-30) to see the extent of the issue, and there's a [lot of red](https://travis-ci.org/jwhitlock/drf-json-api/builds/48136870)

**Comment by jwhitlock** [comment]
I was able to get 2.4 tests working with just changes to tests, so I'm confident drf-json-api works with  both DRF 2.3 and DRF 2.4 on top of Django 1.5 - 1.7.  I'm down to [just the 3.0 tests failing](https://travis-ci.org/jwhitlock/drf-json-api/builds/48138268).  However, there's a lot of changes to code in 3.0, both in tests and the drf-json-api code, so it won't be a quick fix.

**Comment by simonv3** [comment]
Cool, thanks for putting in the effort! I gave porting to 3.0 a quick attempt by creating a serializer class and initializing it with the data class, and then using its get_fields() class. This worked for not returning errors, but when it came to checking for converter_name (`renderers.py:347`), I was a stumped. It probably requires a bit more thorough thought to get all the right types of fields from the data (ie, what the linked serializers are to create the links).

**Comment by kevin-brown** [comment]
Hm, I _thought_ I had the compatibility fixed with https://github.com/kevin-brown/drf-json-api/commit/f281144006b4639a87332cc3fed967e51c8bbf69.

But I also realize now that it's not in a PyPI release.

**Comment by jwhitlock** [comment]
@kevin-brown - Thanks for the sanity check.  I forgot the crucial step of pulling upstream changes into my fork.  My drf24-30 branch was out-of-date, so I dropped it.

I've started a new branch [test_more_env](https://github.com/jwhitlock/drf-json-api/tree/test_more_env), and I'm now seeing the [opposite issue](https://travis-ci.org/jwhitlock/drf-json-api/builds/48170209), that DRF 3.0 passes but DRF 2.3 and 2.4 doesn't.

Is the solution a new PyPI release? @simonv3 can you test against drf-json-api HEAD?

**Comment by kevin-brown** [comment]
> that DRF 3.0 passes but DRF 2.3 and 2.4 doesn't.

Yeah, I noted that in my commit:

> All of the code and tests now pass on DRF 3, but three tests fail
on DRF 2 because of incompatible API changes that are difficult to
test independently.

I know at least two of them are because of spelling changes (capitalization), though I can't remember why the meta one is failing. The solution is probably to just to try checking them independent of the case, though that would require restructuring those tests.

> Is the solution a new PyPI release?

Definitely, once I get the tests passing on all versions.

**Comment by kevin-brown** [comment]
I've pushed a new version up to PyPI that should support DRF 3.0.

**Comment by simonv3** [comment]
I just pulled in the newest from PyPi, and without a thorough look at the endpoints it looks like it all translated properly.

Thanks a bunch for being so responsive on this!
