### ISSUE TITLE
JSON API spec has reached version v1.0.

### ISSUE THREAD

**Issue by jpadilla** [kevin-brown/drf-json-api#35]
The JSON API specification has reached version 1.0 and should be considered stable. Are there any plans to update this package and reach v1.0 compliance?

**Comment by jwhitlock** [comment]
I built my own API on JSON API release candidate 2 (RC2) back in summer 2014, assuming that the changes would be minor on the way to v1.0.  The changes to v1.0 were significant, and there's not a good path forward for me. My API v1 will be RC2, and I'll consider JSON API v1.0 for v2, which is probably 2016 at this rate.  So, I'll probably be forking to support RC2, and it will be 2016 before I can contribute to the v1.0 effort.

**Comment by kevin-brown** [comment]
Merging this back into https://github.com/kevin-brown/drf-json-api/issues/27.

[I have a PR open](https://github.com/kevin-brown/drf-json-api/pull/31) for 1.0.0-rc.3 compatibility, but it's not fully there yet and I'm running low on time for working on it (and I don't have an active project using it).
