### ISSUE TITLE
Status of drf-json-api

### ISSUE THREAD

**Issue by gonvaled** [kevin-brown/drf-json-api#44]
Hi,

I am considering using this project, but I am concerned that the last commit to the master branch was on Feb 18, 2015. JSON API itself reached version 1.0 on the 29.05.2015. Could we get an idea of what is the development status of the project? Are there maybe other active forks?

Thanks!

**Comment by jsenecal** [comment]
Maybe not a fork but another project: https://github.com/django-json-api/django-rest-framework-json-api on the develop branch. 

Full disclosure: I am an active contributor on that project

**Comment by kevin-brown** [comment]
This project is dead, and it won't be coming back to life.

This project has been superseded by https://github.com/django-json-api/django-rest-framework-json-api.
